_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
algorithm:
    value: COPAINT
dataset:
    value: imagenet
mask_type:
    value: wide
n_samples:
    value: 2
sampling_algo:
    value: o_ddim
